# Online-only database profile.
spring.profiles.active=postgres

# Common database configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Jackson configuration
spring.jackson.serialization.write-dates-as-timestamps=false

